#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Game.Droid.Resource", IsApplication=true)]

namespace Game.Droid
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7F010000
			public const int colorAccent = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int colorPrimary = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int colorPrimaryDark = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int launcher_background = 2130771971;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F020000
			public const int action_ability = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int action_attack = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int action_default = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int action_move = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int battleboard = 2130837508;
			
			// aapt resource value: 0x7F020005
			public const int d10 = 2130837509;
			
			// aapt resource value: 0x7F020006
			public const int d20_2 = 2130837510;
			
			// aapt resource value: 0x7F020007
			public const int dungeon_door = 2130837511;
			
			// aapt resource value: 0x7F020008
			public const int elf1 = 2130837512;
			
			// aapt resource value: 0x7F020009
			public const int elf2 = 2130837513;
			
			// aapt resource value: 0x7F02000A
			public const int elf3 = 2130837514;
			
			// aapt resource value: 0x7F02000B
			public const int elf4 = 2130837515;
			
			// aapt resource value: 0x7F02000C
			public const int elf5 = 2130837516;
			
			// aapt resource value: 0x7F02000D
			public const int elf6 = 2130837517;
			
			// aapt resource value: 0x7F02000E
			public const int elf7 = 2130837518;
			
			// aapt resource value: 0x7F02000F
			public const int feet1 = 2130837519;
			
			// aapt resource value: 0x7F020010
			public const int feet2 = 2130837520;
			
			// aapt resource value: 0x7F020011
			public const int hat1 = 2130837521;
			
			// aapt resource value: 0x7F020012
			public const int hat2 = 2130837522;
			
			// aapt resource value: 0x7F020013
			public const int icon_add = 2130837523;
			
			// aapt resource value: 0x7F020014
			public const int icon_cancel = 2130837524;
			
			// aapt resource value: 0x7F020015
			public const int icon_delete = 2130837525;
			
			// aapt resource value: 0x7F020016
			public const int icon_edit = 2130837526;
			
			// aapt resource value: 0x7F020017
			public const int icon_new = 2130837527;
			
			// aapt resource value: 0x7F020018
			public const int icon_save = 2130837528;
			
			// aapt resource value: 0x7F020019
			public const int item = 2130837529;
			
			// aapt resource value: 0x7F02001A
			public const int items = 2130837530;
			
			// aapt resource value: 0x7F02001B
			public const int knight = 2130837531;
			
			// aapt resource value: 0x7F02001C
			public const int neck1 = 2130837532;
			
			// aapt resource value: 0x7F02001D
			public const int neck2 = 2130837533;
			
			// aapt resource value: 0x7F02001E
			public const int ring1 = 2130837534;
			
			// aapt resource value: 0x7F02001F
			public const int ring2 = 2130837535;
			
			// aapt resource value: 0x7F020020
			public const int score = 2130837536;
			
			// aapt resource value: 0x7F020021
			public const int shield1 = 2130837537;
			
			// aapt resource value: 0x7F020022
			public const int shield2 = 2130837538;
			
			// aapt resource value: 0x7F020023
			public const int shield3 = 2130837539;
			
			// aapt resource value: 0x7F020024
			public const int shield4 = 2130837540;
			
			// aapt resource value: 0x7F020025
			public const int sword1 = 2130837541;
			
			// aapt resource value: 0x7F020026
			public const int sword10 = 2130837542;
			
			// aapt resource value: 0x7F020027
			public const int sword11 = 2130837543;
			
			// aapt resource value: 0x7F020028
			public const int sword2 = 2130837544;
			
			// aapt resource value: 0x7F020029
			public const int sword3 = 2130837545;
			
			// aapt resource value: 0x7F02002A
			public const int sword4 = 2130837546;
			
			// aapt resource value: 0x7F02002B
			public const int sword5 = 2130837547;
			
			// aapt resource value: 0x7F02002C
			public const int sword6 = 2130837548;
			
			// aapt resource value: 0x7F02002D
			public const int sword7 = 2130837549;
			
			// aapt resource value: 0x7F02002E
			public const int sword8 = 2130837550;
			
			// aapt resource value: 0x7F02002F
			public const int sword9 = 2130837551;
			
			// aapt resource value: 0x7F020030
			public const int troll = 2130837552;
			
			// aapt resource value: 0x7F020031
			public const int troll1 = 2130837553;
			
			// aapt resource value: 0x7F020032
			public const int troll2 = 2130837554;
			
			// aapt resource value: 0x7F020033
			public const int troll3 = 2130837555;
			
			// aapt resource value: 0x7F020034
			public const int troll4 = 2130837556;
			
			// aapt resource value: 0x7F020035
			public const int troll5 = 2130837557;
			
			// aapt resource value: 0x7F020036
			public const int troll6 = 2130837558;
			
			// aapt resource value: 0x7F020037
			public const int village = 2130837559;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Mipmap
		{
			
			// aapt resource value: 0x7F030000
			public const int icon = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int icon_round = 2130903041;
			
			// aapt resource value: 0x7F030002
			public const int launcher_foreground = 2130903042;
			
			static Mipmap()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Mipmap()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7F040000
			public const int MainTheme = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
